# Generated by Django 3.1.2 on 2020-10-12 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='email',
            field=models.EmailField(default='e@g.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donator',
            name='first_name',
            field=models.CharField(default='JJ', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donator',
            name='last_name',
            field=models.CharField(default='Jonah', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='donator',
            name='phone',
            field=models.IntegerField(default=88),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='donator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
