# Generated by Django 3.1.2 on 2020-10-14 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20201012_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('addr', models.TextField()),
                ('donators', models.ManyToManyField(to='accounts.Donator')),
            ],
        ),
    ]
