# Generated by Django 3.1.2 on 2020-10-14 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='donators',
        ),
        migrations.AddField(
            model_name='donator',
            name='addresses',
            field=models.ManyToManyField(to='accounts.Address'),
        ),
    ]
