# Generated by Django 3.1.2 on 2020-10-16 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201014_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donator',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
