# Generated by Django 3.1.2 on 2020-10-17 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201016_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
