# Generated by Django 3.1.2 on 2020-10-17 04:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201016_1749'),
        ('accounts', '0008_auto_20201016_1801'),
    ]

    operations = [
    ]
