# Generated by Django 3.1.2 on 2020-10-17 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20201017_0955'),
    ]

    operations = [
        migrations.AddField(
            model_name='donator',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
