# Generated by Django 3.1.2 on 2020-10-11 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='user',
            new_name='donator',
        ),
    ]
