# Generated by Django 3.1.2 on 2020-10-11 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20201011_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='donator',
        ),
        migrations.DeleteModel(
            name='Donator',
        ),
    ]
