# Generated by Django 3.1.2 on 2020-10-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20201011_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='added_at',
            field=models.DateTimeField(default='2020-10-11 14:16:19'),
            preserve_default=False,
        ),
    ]
