# Generated by Django 3.1.2 on 2020-10-14 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201014_2100'),
        ('food', '0004_food_added_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='donator',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='accounts.donator'),
            preserve_default=False,
        ),
    ]
