# Generated by Django 3.1.2 on 2020-10-14 23:44

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201014_2100'),
        ('food', '0005_food_donator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='address',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='donator', chained_model_field='donator', on_delete=django.db.models.deletion.CASCADE, to='accounts.address'),
        ),
    ]
