# Generated by Django 3.1.2 on 2020-10-16 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0006_auto_20201014_2344'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(default='food/default.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
