# Generated by Django 3.1.2 on 2020-10-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_food_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['expiry']},
        ),
        migrations.AddField(
            model_name='food',
            name='tag',
            field=models.CharField(blank=True, choices=[('T', 'Tentative'), ('E', 'Emergency'), ('S', 'Expiring soon')], max_length=2, null=True),
        ),
    ]
