# Generated by Django 3.1.2 on 2020-10-16 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_auto_20201016_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='tag',
            field=models.CharField(choices=[('T', 'Tentative'), ('E', 'Emergency'), ('S', 'Expiring soon'), ('N', 'None')], default='N', max_length=2),
        ),
    ]
