# Generated by Django 3.1.2 on 2020-10-16 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_auto_20201016_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='lat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='food',
            name='lon',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
