# Generated by Django 3.1.2 on 2020-10-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0010_auto_20201016_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
