# Generated by Django 3.1.2 on 2020-10-16 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0011_auto_20201016_1732'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={},
        ),
    ]
