# Generated by Django 3.1.2 on 2020-10-16 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_auto_20201016_1817'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
