# Generated by Django 3.1.2 on 2020-10-17 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_food_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='food',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='food',
            name='lon',
        ),
    ]
