# Generated by Django 3.1.2 on 2020-10-17 03:37

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_auto_20201017_0906'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
